### ISSUE TITLE
implementation?

### ISSUE THREAD

**Issue by fitbodylife** [ako977/tokenSessionService#1]
how do i implement this in my joomla site?

**Comment by ako977** [comment]
Hi, this is an angular js service plugin, so it would be something that plugs in to your angular js app as a module, it would not need to know if the backend is joomla or otherwise. If you are concerned about adding it to your frontend content in joomla, I am not experienced in joomla so wouldn't know the details, but I would say to add it in the same way you would add in an angular js app.
